#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial
# Copyright (C) 2026 Louis Nelson Jr. <https://lousclues.com>
#
# Scoped sudo entry point for ip6tables. Granted passwordless via
# /etc/sudoers.d/shroud; delegates argument validation to shroud-fw-lib.sh.
SHROUD_FW_TOOL=ip6tables
for c in /usr/sbin/ip6tables /usr/bin/ip6tables /sbin/ip6tables /bin/ip6tables; do
    [ -x "$c" ] && { SHROUD_FW_REAL="$c"; break; }
done
export SHROUD_FW_TOOL SHROUD_FW_REAL
. /usr/local/lib/shroud/shroud-fw-lib.sh
